# 混合端口 HTTP和SOCKS5用一个端口
mixed-port: 7890

# HTTP 代理端口
# port: 7890

# SOCKS5 代理端口
# socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 仅在将allow-lan设置为true时适用
# #"*": 绑定所有IP地址
# #192.168.122.11: 绑定单个IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"
ipv6: true

# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent

# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true
  # interface-name: en0 # outbound interface name

# 本地 SOCKS5 / HTTP(S) 服务认证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效

dns:
  enable: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - https://9.9.9.9/dns-query
    - https://208.67.222.222/dns-query
    - https://77.88.8.8/dns-query
    - tls://dns.sse.cisco.com
    - tls://dns.umbrella.com
  direct-nameserver:
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  nameserver-policy:
    +.cloudflareclient.com: tls://1.1.1.1:853
    +.securelogin.com.cn: system
    captive.apple.com: system
    hotspot.cslwifi.com: system
    "*.m2m": system
    injections.adguard.org: system
    local.adguard.org: system
    "*._tcp": system
    "*.bogon": system
    "*._msdcs": system
    +.msftncsi.com: system
    "geosite:private": system
    "geosite:cn": https://223.5.5.5/dns-query#h3=true
    "国内媒体": https://223.5.5.5/dns-query#h3=true
    "国内站点": https://223.5.5.5/dns-query#h3=true
    "哔哩哔哩": https://223.5.5.5/dns-query#h3=true
    "网易云音乐": https://223.5.5.5/dns-query#h3=true
  respect-rules: true
  ipv6: true
  fake-ip-filter:
    - +.example
    - +.invalid
    - +.localhost
    - +.test
    - +.local
    - +.+m2m
    - +.$injections.adguard.org
    - +.$local.adguard.org
    - +.+_tcp
    - +.+bogon
    - +.+_msdcs
    - +.+lan
    - +.+localdomain
    - +.home.arpa
    - +.10.in-addr.arpa
    - +.16.172.in-addr.arpa
    - +.17.172.in-addr.arpa
    - +.18.172.in-addr.arpa
    - +.19.172.in-addr.arpa
    - +.20.172.in-addr.arpa
    - +.21.172.in-addr.arpa
    - +.22.172.in-addr.arpa
    - +.23.172.in-addr.arpa
    - +.24.172.in-addr.arpa
    - +.25.172.in-addr.arpa
    - +.26.172.in-addr.arpa
    - +.27.172.in-addr.arpa
    - +.28.172.in-addr.arpa
    - +.29.172.in-addr.arpa
    - +.30.172.in-addr.arpa
    - +.31.172.in-addr.arpa
    - +.168.192.in-addr.arpa
    - +.254.169.in-addr.arpa
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - ntp.ntsc.ac.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - ntp.*.cn
    - clock.neu.edu.cn
    - time1.cloud.tencent.com
    - time-ios.apple.com
    - +.music.163.com
    - +.126.net
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - +.kuwo.cn
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - +.xiami.com
    - +.music.migu.cn
    - +.msftconnecttest.com
    - +.msftncsi.com
    - WORKGROUP
    - +.localhost.ptlogin2.qq.com
    - +.localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.xbox.*.microsoft.com
    - +.xnotify.xboxlive.com
    - +.ipv6.microsoft.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - +.stun.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.pvp.net
    - +.heartbeat.belkin.com
    - +.linksys.com
    - +.linksyssmartwifi.com
    - +.router.asus.com
    - +.mesu.apple.com
    - +.swscan.apple.com
    - +.swquery.apple.com
    - +.swdownload.apple.com
    - +.swcdn.apple.com
    - +.swdist.apple.com
    - +.lens.l.google.com
    - +.stun.l.google.com
    - fcm.googleapis.com
    - mtalk.google.com
    - alt*-mtalk.google.com
    - +.push.hicloud.com
    - +.push.dbankcloud.com
    - api.xmpush.xiaomi.com
    - +.push.apple.com
    - +.push.oppomobile.com
    - api-push.vivo.com.cn
    - +.nflxvideo.net
    - +.square-enix.com
    - +.finalfantasyxiv.com
    - +.ffxiv.com
    - +.ff14.sdo.com
    - ff.dorado.sdo.com
    - +.mcdn.bilivideo.cn
    - +.media.dssott.com
