mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: true
udp: true
log-level: warning
external-controller: 127.0.0.1:9090
# external-ui: ui
# external-ui-url: 'https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
unified-delay: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true
geox-url:
  geoip: 'https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat'
  geosite: 'https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat'
  mmdb: 'https://gitlab.com/Masaiki/GeoIP2-CN/-/raw/release/Country.mmdb'
  asn: 'https://gitlab.com/Loon0x00/loon_data/-/raw/main/geo/GeoLite2-ASN.mmdb'
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  enhanced-mode: fake-ip
  prefer-h3: true
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - h3://223.5.5.5/dns-query
  fallback:
    - https://208.67.222.222/dns-query
    - https://9.9.9.9/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
  follow-rule: true
  ipv6: true
  fake-ip-filter:
    - +.example
    - +.invalid
    - +.localhost
    - +.test
    - +.local
    - +.+m2m
    - +.$injections.adguard.org
    - +.$local.adguard.org
    - +.+_tcp
    - +.+bogon
    - +.+_msdcs
    - +.+lan
    - +.+localdomain
    - +.home.arpa
    - +.10.in-addr.arpa
    - +.16.172.in-addr.arpa
    - +.17.172.in-addr.arpa
    - +.18.172.in-addr.arpa
    - +.19.172.in-addr.arpa
    - +.20.172.in-addr.arpa
    - +.21.172.in-addr.arpa
    - +.22.172.in-addr.arpa
    - +.23.172.in-addr.arpa
    - +.24.172.in-addr.arpa
    - +.25.172.in-addr.arpa
    - +.26.172.in-addr.arpa
    - +.27.172.in-addr.arpa
    - +.28.172.in-addr.arpa
    - +.29.172.in-addr.arpa
    - +.30.172.in-addr.arpa
    - +.31.172.in-addr.arpa
    - +.168.192.in-addr.arpa
    - +.254.169.in-addr.arpa
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - ntp.ntsc.ac.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - ntp.*.cn
    - clock.neu.edu.cn
    - time1.cloud.tencent.com
    - time-ios.apple.com
    - +.music.163.com
    - +.126.net
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - +.kuwo.cn
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - +.xiami.com
    - +.music.migu.cn
    - +.msftconnecttest.com
    - +.msftncsi.com
    - WORKGROUP
    - +.localhost.ptlogin2.qq.com
    - +.localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.xbox.*.microsoft.com
    - +.xnotify.xboxlive.com
    - +.ipv6.microsoft.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - +.stun.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.pvp.net
    - +.heartbeat.belkin.com
    - +.linksys.com
    - +.linksyssmartwifi.com
    - +.router.asus.com
    - +.mesu.apple.com
    - +.swscan.apple.com
    - +.swquery.apple.com
    - +.swdownload.apple.com
    - +.swcdn.apple.com
    - +.swdist.apple.com
    - +.lens.l.google.com
    - +.stun.l.google.com
    - fcm.googleapis.com
    - mtalk.google.com
    - alt*-mtalk.google.com
    - +.push.hicloud.com
    - +.push.dbankcloud.com
    - api.xmpush.xiaomi.com
    - +.push.apple.com
    - +.push.oppomobile.com
    - api-push.vivo.com.cn
    - +.nflxvideo.net
    - +.square-enix.com
    - +.finalfantasyxiv.com
    - +.ffxiv.com
    - +.ff14.sdo.com
    - ff.dorado.sdo.com
    - +.mcdn.bilivideo.cn
    - +.media.dssott.coms
  nameserver-policy:
    captive.apple.com: system
    "国内媒体": https://223.5.5.5/dns-query#h3=true
    "国内站点": https://223.5.5.5/dns-query#h3=true
    "哔哩哔哩": https://223.5.5.5/dns-query#h3=true
    "网易云音乐": https://223.5.5.5/dns-query#h3=true
    "geosite:cn,private": https://223.5.5.5/dns-query#h3=true
